import numpy as np

LIBRISPEECH_SAMPLE_RATE = 44100
LIBRISPEECH_WINDOW_SIZE = 512
LIBRISPEECH_COMPONENTS = LIBRISPEECH_WINDOW_SIZE // 2 + 1
EPSILON = 1e-8
STFT_CROP_WIDTH = 64

SPEAKER_DATA_PATH = "data/processed/LibriSpeech/SPEAKERS.TXT"

NUMBER_OF_CLASSES = 2  # female, male

MAGNITUDE_NONLINEARITY = 1 / 8
DATA_MEANS = np.asarray([0.16460373, -0.00396298])
